For React native 0.62 version

So I figure it out

Replace following line in your Podfile

pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
with

pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
Edit:

If you have updated to React Native version 0.63

Delete Podfile.lock from iOS folder. Do npm i

Open podfile from iOS folder

Delete everything and copy below contents

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

target 'fluapp' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'RNTodoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RNTodo-tvOS' do
  # Pods for RNTodo-tvOS

  target 'RNTodo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end